# Generated by Django 2.2.1 on 2019-05-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190518_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='release_groups',
        ),
        migrations.AddField(
            model_name='artist',
            name='music_releases',
            field=models.ManyToManyField(blank=True, to='core.MusicRelease'),
        ),
    ]
